config/routes.rb
Rails.application.routes.draw do

  root to: 'tops#top'
  resources :contacts do
    resources :responses
    collection do
      post :confirm
    end
  end

  resources :sessions, only:[:new, :create, :destroy]
  resources :users
  resources :favorites, only:[:create, :destroy, :show, :index]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :title, presence: true, length: {in: 1..500 }
  validates :content, presence: true, length: {in: 1..500}

  belongs_to :user
  has_one :favorite
  #has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user

  has_many :responses, dependent: :destroy
  
  mount_uploader :image, ImageUploader
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :contact
end

app/models/response.rb
class Response < ApplicationRecord
  validates :content, presence: true, length: {in: 1..140}

  belongs_to :contact
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
            format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }

  before_validation { email.downcase! }

  has_secure_password
  validates :password, presence: true, length: { minimum: 6}

  has_many :contacts
  has_many :favorites, dependent: :destroy
  has_many :favorite_contacts, through: :favorites, source: :contact

  has_many :responses

  mount_uploader :icon, IconUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only:[:show, :edit, :update, :destroy]
  before_action :login_check, only:[:index, :new, :edit, :show, :destroy]
  before_action :current_check, only: :edit

  def index
    @contacts = Contact.all
  end

  def new
    if params[:back]
      @contact = Contact.new(contact_params)
    else
      @contact = Contact.new
    end
  end

  def create
    @contact = Contact.new(contact_params)
    @contact.user_id = current_user.id
    if @contact.save
      #ContactMailer.contact_mail(@contact).deliver
      redirect_to contacts_path, notice: "問い合わせ中･･･"
    else
      render 'new'
    end
  end

  def show
    @contact = Contact.find(params[:id])

    @favorite = current_user.favorites.find_by(contact_id: @contact.id)
    @favorites = Favorite.find_by(contact_id: @contact.id)
    

    @responses = @contact.responses.includes(:user).all
    @response = @contact.responses.build(user_id: current_user.id) if current_user
  end
  
  def edit
    @contact = Contact.find(params[:id])
  end



  def update
    @contact = Contact.find(params[:id])
    if @contact.update(contact_params)
      redirect_to contacts_path, notice: "投稿内容を更新しました"
    else
      render 'edit'
    end
  end

  def destroy
    @contact.destroy
    redirect_to contacts_path, notice: "投稿を削除しました"
  end

  def confirm
    @contact = Contact.new(contact_params)
    @contact.user_id = current_user.id
    render :new if @contact.invalid?
  end
  
  private

  def contact_params
    params.require(:contact).permit(:title,:content, :image, :image_cache)
  end

  def set_contact
    @contact = Contact.find(params[:id])
  end

  def login_check
    unless current_user
      render new_session_path
    end
  end
  
  def current_check
      @contact = Contact.find(params[:id])
    unless @contact.user_id == current_user.id  
      redirect_to contacts_path
    end
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    favorite = current_user.favorites.create(contact_id: params[:contact_id])
    redirect_to contacts_url, notice: "#{favorite.contact.user.name}さんの投稿をお気に入りしました"
  end

  def destroy
    favorite = current_user.favorites.find_by(id: params[:id]).destroy
    redirect_to contacts_url, notice: "#{favorite.contact.user.name}さんの投稿をお気に入り解除しました"
  end

  def show
    @user = User.find(session[:user_id])
    @favorite_contacts = @user.favorite_contacts
  end
  

  #追加
  #def index
    #@user = current_user
    #@favorites = Favorite.where(user_id: @user.id).all
  #end

  def show_favorites
    @contact = Contact.find(params[:id])
    @favorites = Favorite.find_by(contact_id: @contact.id)
  end
  
  private

  def contact_params
    params.require(:contact).permit(:title,:content, :image, :image_cache)
  end
end

  def login_check
    unless current_user
      render new_session_path
    end
  end

app/controllers/responses_controller.rb
class ResponsesController < ApplicationController
  def create
    @contact = Contact.find(params[:contact_id])

    @response = @contact.responses.build(response_params)
    @responses = @contact.responses
    @response.user_id = current_user.id
    respond_to do |format|
      if @response.save
        format.js { render :index }
      else
        format.html { redirect_to contact_path(@contact), notice: '投稿に失敗しました' }
      end
    end
  end

private

  def response_params
    params.require(:response).permit(:contact_id, :content, :created_at, :user_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash.now[:danger] = 'ログイン失敗'
      render 'new'
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウト完了'
    redirect_to new_session_path
  end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  def top
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to contacts_path(@user.id), notice: "アカウントを作成しました"
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
    #追加
    @favorites = Favorite.where("user_id = ?", @user)
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :icon, :icon_cache)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm'
      confirm_contacts_path
    elsif action_name == 'edit'
      contact_path
    end
  end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/responses_helper.rb
module ResponsesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/contacts/_form.html.erb
   <%= form_with(model: @contact, local: true, url: choose_new_or_edit) do |form| %>
     <% if @contact.errors.any? %>
       <div id="error_expanation">
       <p class="alert alert-danger"><%= @contact.errors.count %>件のエラーがあります。</p>
       <ul class="alert_reason">
         <% @contact.errors.full_messages.each do |msg| %>
           <li><%= msg %></li>
         <% end %>
       </ul>
       </div>
     <% end %>

     <div class="contact_title">
       <div class="form-group, col-md-6">
        <%= form.label :title %>
        <%= form.text_field :title, class: 'form-control'%>
      </div>
     <br>
     </div>
     
     <div class="contact_title">
       <div class="form-group, col-md-6">
        <%= form.label :content %>
        <%= form.text_area :content, class: 'form-control', rows: "3" %>
        <p class="help-block">1~500文字以内で入力してください。</p>
       </div>
     </div>
     
     <br>
     <div class="contact_title">
      <div class="form-group, col-md-6">
      <%= image_tag(@contact.image.url) if @contact.image.url %>
      <%= form.file_field :image, id: :feed_image %>
      </div>
     
     
     <br>
    <div class="contact_title">
    <div class="form-group, col-md-6">
    <%= form.submit "投稿", class: 'btn btn-default btn-sm btn-success' %>
    </div>
    </div>
   <% end %>
   
  

app/views/contacts/confirm.html.erb
<div class="container">
  <div class="row">
   <div class="col-lg-12">

   <h3>投稿内容確認画面</h3>

    <%= form_with(model: @contact, url: contacts_path, local: :true) do |form| %>
      <%= form.hidden_field :title %>
      <%= form.hidden_field :content %>
      <%= form.hidden_field :image_cache %>

       <p>件名:<%= @contact.title %></p>
       <p>本文:<%= @contact.content %></p>
       <p>画像:</p>
       <p><%= image_tag(@contact.image) %></p>
       <%= form.submit "投稿", class: 'btn btn-default btn-sm btn-success' %>
    <% end %>
    <br>
    <%= form_with(model: @contact, url: new_contact_path, local: :true, method: 'get') do |form| %>
       <%= form.hidden_field :title %>
       <%= form.hidden_field :content %>
       <%= form.hidden_field :image_cache %>
       <%= form.submit "戻る", name: 'back' , class: 'btn btn-default btn-sm btn-default' %>
    <% end %>
    </div>
  </div>
</div>

app/views/contacts/edit.html.erb
<div class="container">
  <div class="row">
   <div class="col-lg-12">

   <h1>投稿内容を編集する</h1>

   <%= render 'form' %>
   
   </div>
  </div>
</div>

app/views/contacts/index.html.erb
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <h1>問い合わせ一覧</h1>
          <div id ="new-contact-link">
            <%= link_to '新規問い合わせ', new_contact_path, class: 'btn btn-default btn-sm btn btn-success' %>
          </div>
          <br>
            <% @contacts.each do |contact| %>
            <% user = User.find_by(id: contact.user_id) %>
              <p>投稿者：<%= user.name %></p>
              <p>件名：<%= contact.title %></p>
              <p>内容：<%= contact.content %></p>
              <P>作成日時：<%= contact.created_at.in_time_zone('Tokyo').strftime("%Y-%m-%d %H:%M") %></p>
              <p><%= image_tag contact.image %></p>
              <%= link_to '詳細', contact_path(contact.id), class: 'btn btn-default btn-sm btn-default' %>
              <% if contact.user_id == current_user.id %>
              <%= link_to '編集', edit_contact_path(contact.id), data:{confirm: '編集ますか？'}, class: 'btn btn-default btn-sm btn-info' %> 
              <%= link_to '削除', contact_path(contact.id), method: :delete, data:{confirm: '本当に削除しますか？'}, class: 'btn btn-default btn-sm btn btn-danger' %>
              <% end %>
              <br>
              <br>
            <% end %>
       </div>
    </div>
</div>

app/views/contacts/new.html.erb
<div class="container">
  <div class="row">
   <div class="col-lg-12">

   <h1>新規問い合わせ</h1>

   <%= render 'form' %>

   </div>
  </div>
</div>

app/views/contacts/show.html.erb
<div class="container">
  <div class="row">
   <div class="col-lg-12">

   <h1>問い合わせ詳細</h1>
   <div class="col-md-6">
     <p>件名：<%= @contact.title %></p>
     <p>内容：<%= @contact.content %></p>
     <p><%= image_tag @contact.image %></p>
     
         <% unless @contact.user_id == current_user.id %>
             <% if @favorite.present? %>
　                <% if @favorites.user_id == current_user.id %>
                       <%= link_to 'お気に入り解除する', favorite_path(id: @favorite.id),
                       method: :delete, class: 'btn btn-default btn-sm btn btn-danger' %>
                  <% else %>
                       <%= link_to 'お気に入りにする', favorites_path(contact_id: @contact.id),
                       method: :post, class: 'btn btn-default btn-sm btn btn-primary' %>
                  <% end %>
             <% else %>
                <% if @favorites.nil? %>
                    <%= link_to 'お気に入りにする', favorites_path(contact_id: @contact.id),
                    method: :post, class: 'btn btn-default btn-sm btn btn-primary' %>
            　　<% else %>
            　　<p>この投稿の担当者は <%= @favorites.user.name %>さんです</p>
                <% end %>
             <% end %>
        <% end %>
        
　　　　
   </div>
   <div class="col-md-6">
     <h3>コメント一覧</h3>
     <div id="responses_area">
       <%= render partial: 'responses/index', locals: { responses: @responses, contact: @contact } %>
     </div>
       <%= render partial: 'responses/form', locals: { response: @response, contact: @contact } %>
   </div>

   <div class="col-md-6">
    <%= link_to "一覧画面にもどる", contacts_path, class: 'btn btn-default btn-sm btn btn-default' %>
   </div>
   </div>
  </div>
</div>

app/views/favorites/reference/index.html.erb
<h2>参加中のイベント</h2>
    <% @favorites.each do |favorite| %>
      <% contact = Event.find(favorite.contact_id) %>
            <div class="name3"><%= link_to contact.contact_name, contact_path(contact) %></div>
            <div class="name2"><%= link_to "参加中のイベントから削除",favorite_path(favorite), method: :delete %></div>
            <div class="name2">
            <%= contact.contact_date.strftime("%Y-%m-%d %H:%M:%S")  %>
            </div>
            <div class="name2">
            <%= contact.contact_location %>
            </div>
    <br />
    <% end %>

app/views/favorites/show.html.erb
<div class="container">
  <div class="row">
   <div class="col-lg-12">

   <h1>お気に入り一覧</h1>
     <br>
     <% if @favorite_contacts.present? %>
       <% @favorite_contacts.each do |t| %>
       <div class="contact-panel">
         <p>投稿者：<%= t.user.name %></p>
         <p>件名：<%= t.title %></p>
         <p>内容：<%= t.content %></p>
         <p><%= image_tag t.image %><p>
       </div>
       <% end %>
     <% end %>
     <br>
     
      <%= link_to "一覧画面にもどる", contacts_path, class: 'btn btn-default btn-sm btn btn-default' %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en-US" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!--  
    Document Title
    =============================================
    -->
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>

    <title>ContactForm</title>

    <!-- Custom fonts for this template -->
    <header>
      <!-- Navigation -->
      <nav class="navbar navbar-default">
            <div class="container-fluid">
              <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#gnavi">
                  <span class="sr-only">Bootstrap</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                </button>
               <a class="navbar-brand" href="/"></a>
              </div>
              <div id="gnavi" class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                  <li><%= link_to "TOP", root_path %></li>
                  <li><%= link_to "お問い合わせ一覧", contacts_path %></li>
                  <li><%= link_to "新規お問い合わせ", new_contact_path %></li>
                  <% if logged_in? %>
                    <li><%= link_to "プロフィール", user_path(current_user.id) %></li>
                    <li><%= link_to "ログアウト", session_path(current_user.id), method: :delete %></li>
                  <% else %>
                    <li><%= link_to "サインアップ", new_user_path %></li>
                    <li><%= link_to "ログイン", new_session_path %></li>
                  <% end %>
                 </ul>
               </div>
             </div>
           </nav>
         </header>
    </head>

    <body>
      <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
      <% end %>

      <%= yield %>

    </body>
</html>

app/views/responses/_form.html.erb
<%= form_with(model: [contact, response]) do |form| %>
  <% if response.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(response.errors.count, "") %>件のエラーがあります。</h2>
      <ul>
      <% response.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.text_area :content, placeholder: '返信する', class: 'form-control', rows: "3" %>
  </div>
  <br>
  <div class="actions">
  <%= form.submit "返信する", class: 'btn btn-default btn-sm btn-success' %>
  </div>
<% end %>
<br>

app/views/responses/_index.html.erb
<ul class="response">
  <% responses.each do |response| %>
    <% if response.id.present? %>
      <li>
        <% user = User.find_by(id: response.user_id) %>
        <p>投稿者：<%= user.name %></p>
        <p>件名：<%= response.content %></p>
        <p><%= response.created_at.in_time_zone('Tokyo').strftime("%Y-%m-%d %H:%M") %></p>
        <br>
      </li>
    <% end %>
  <% end %>
</ul>

app/views/responses/create.html.erb
<h1>Responses#create</h1>
<p>Find me in app/views/responses/create.html.erb</p>

app/views/responses/index.js.erb
$("#responses_area").html("<%= j(render 'responses/index', { responses: @response.contact.responses, contact: @response.contact, }) %>")
$("textarea").val('')

app/views/tops/top.html.erb
<!-- Page Header -->
<header class="masthead" style="background-image: url(<%= asset_path "top_contact.jpg" %>)">
  <div class="overlay"></div>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <div class="site-heading">
          <h1>log in or sign up to continue</h1>
        </div>
      </div>
    </div>
  </div>
</header>

<!-- Footer -->
<footer>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <p class="copyright text-muted">問い合わせフォームです。どんな質問にもお答えします。 </p>
      </div>
    </div>
  </div>
</footer>

app/views/users/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12">

    <h1>サインアップ</h1>

    <%= form_with(model: @user, local: true) do |f| %>
      <% if @user.errors.any? %>
        <div id="error_explanation">
          <p class="alert alert-danger"><%= pluralize(@user.errors.count, "") %> 件のエラーがあります。</p>
          <ul class="alert_reason">
            <% @user.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group, col-md-6">
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control', placeholder: '名前' %>
      </div>
      <div class="form-group, col-md-6">
        <%= f.label :email %>
        <%= f.email_field :email, class: 'form-control', placeholder: 'メールアドレス' %>
      </div>
      <div class="form-group, col-md-6">
        <%= f.label :password %>
        <%= f.password_field :password, class: 'form-control', placeholder: 'パスワード（6文字以上）' %>
      </div>
      <div class="form-group, col-md-6">
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation, class: 'form-control', placeholder: 'パスワード（再入力）' %>
      </div>

      <div class="form-group, col-md-6">
        <p><%= f.file_field :icon, id: :feed_icon %></p>
        <p><%= f.hidden_field :icon_cache %><br></p>
      </div>
      <div class="form-group, col-md-6">
        <p><%= f.submit "利用開始登録", class: 'btn btn-default btn-sm btn btn-primary' %></p>
      </div>

    <% end %>

    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
   <div class="col-lg-12">

　 <p>プロフィール</p>
   <h1><%= @user.name %></h1>

   <p>メールアドレス：<%= @user.email %></p>
   <p><%= image_tag @user.icon %></p>
   <br>
   <p><%= link_to 'お気に入り一覧', favorite_path, class: 'btn btn-default btn-sm btn btn-primary' %></p>
   </div>
  </div>
</div>